import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import styled from "styled-components";
import Header from "../components/Header";
import Left from "../components/Left";
import Middle from "../components/Middle";
import Right from "../components/Right";

export const Container = styled.div`
  display: grid;
  grid-template-columns: 2fr 2fr 1fr;
  grid-template-rows: 80px calc(100vh - 80px) 1fr;
  grid-template-areas:
    "header header header"
    "left middle right";

  /* overflow-y: hidden; */
`;

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Left></Left>
      <Middle></Middle>
      <Right></Right>
    </Container>
  );
}
